# same Dockerfile as payloadcms, but renamed .js to .cjs
# - payload.config.cjs
# - server.mjs
# added python3

# FROM node:18.8-alpine as base
FROM node:alpine3.18 as base

FROM base as builder

WORKDIR /home/node/app
COPY package*.json ./

COPY . .

RUN apk --no-cache add --virtual python3
RUN yarn install
RUN yarn docker:build:yarn

FROM base as runtime

ENV NODE_ENV=production
ENV PAYLOAD_CONFIG_PATH=dist/payload.config.cjs

WORKDIR /home/node/app

COPY package*.json  ./

# RUN yarn config set strict-ssl false
RUN yarn install --production
RUN yarn cache clean

COPY --from=builder /home/node/app/dist ./dist
COPY --from=builder /home/node/app/build ./build

EXPOSE 3000

CMD ["node", "dist/server.mjs"]